#
# Copyright (c) 2025 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

---
apiVersion: "helm.toolkit.fluxcd.io/v2"
kind: HelmRelease
metadata:
  name: prometheus-openstack-exporter
  labels:
    chart_group: prometheus-openstack-exporter
spec:
  releaseName: osh-prometheus-openstack-exporter
  chart:
    spec:
      chart: prometheus-openstack-exporter
      version: 0.1.9
      sourceRef:
        kind: HelmRepository
        name: starlingx
  interval: 1m
  timeout: 30m
  test:
    enable: false
  install:
    disableHooks: false
  upgrade:
    disableHooks: false
  dependsOn:
    - name: keystone
      namespace: openstack
  valuesFrom:
    - kind: Secret
      name: prometheus-openstack-exporter-static-overrides
      valuesKey: prometheus-openstack-exporter-static-overrides.yaml
    - kind: Secret
      name: prometheus-openstack-exporter-system-overrides
      valuesKey: prometheus-openstack-exporter-system-overrides.yaml
...
